import torch
import os
from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer

def generate_section(model, tokenizer, index, topic, section_name, max_tokens=600):
    messages = [
        {"role": "system", "content": f"You are a distinguished AI medical researcher writing an IEEE-format research paper titled '{topic}'. Output exactly in Markdown formatting, without enclosing the entire output in backticks. Focus only on the section requested. Do not include any preambles."},
        {"role": "user", "content": f"Write the '{section_name}' section for the paper '{topic}'. Return ONLY the text for this section under an appropriate Markdown heading."}
    ]
    
    input_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(input_text, return_tensors="pt").to(model.device)
    
    with torch.no_grad():
        generated_ids = model.generate(
            **inputs,
            max_new_tokens=max_tokens,
            temperature=0.7,
            do_sample=True,
            repetition_penalty=1.1
        )
        
    input_len = inputs["input_ids"].shape[1]
    generated_text = tokenizer.batch_decode(generated_ids[:, input_len:], skip_special_tokens=True)[0]
    return generated_text.strip()


from peft import PeftModel
from transformers import AutoModelForCausalLM

def main():
    MODEL_DIR = "./qwen-xray-researcher"
    BASE_MODEL = "Qwen/Qwen2.5-1.5B-Instruct"  # or whichever base model you used!
    TOPIC = "Vision Transformers for Weakly Supervised Pneumonia Detection"
    OUTPUT_FILE = "qwen_thesis_draft.md"
    
    print(f"Loading Base Model...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)
    
    # Load base model first
    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        torch_dtype=torch.float16,
        #device_map="auto",
        low_cpu_mem_usage=True
    )
    
    print(f"Loading Adapter from {MODEL_DIR}...")
    model = PeftModel.from_pretrained(base_model, MODEL_DIR)
    model.eval()

    sections = [
        "Abstract",
        "1. Introduction", 
        "2. Related Work",
        "3. Methodology"
    ]

    print(f"Generating paper draft: '{TOPIC}'")
    
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(f"# {TOPIC}\n\n")
        f.write("*Auto-Generated by QA\n\n")
    
    for idx, sec in enumerate(sections):
        print(f"  Generating [{sec}]...")
        # Intro might need more tokens
        tokens = 800 if "Introduction" in sec or "Methodology" in sec else 400
        content = generate_section(model, tokenizer, idx, TOPIC, sec, max_tokens=tokens)
        
        with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
            f.write(content + "\n\n")
        
        print(f"  [{sec}] saved.")

    print(f"Draft successfully saved to {OUTPUT_FILE}!")

if __name__ == "__main__":
    main()
